### ISSUE TITLE
也是遇到同样的需求谷歌搜到的这里

### ISSUE THREAD

**Issue by jiqing112** [kemege/pyCAJ2PDF#2]
可是已经停止开发四年了

**Comment by kemege** [comment]
这个基本没啥用的半成品居然还能被搜到。。。
其他人貌似已经做出可以用的工具了。。 https://github.com/JeziL/caj2pdf

**Comment by jiqing112** [comment]
因为有需求嘛，关注中

**Comment by HinTak** [comment]
@kemege 那個android libreaderex 的反編譯很有用，所以接近完成caj2pdf的HN檔轉換了。想看Linux libreaderex_x64.so （cajviewer出了Linux 版…）的反編譯...
